//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SQL.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISQLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SQLBaseListener : ISQLListener {
	public bool shouldBeAssigning = false;
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SQLParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SQLParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.basicSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicSelectStatement([NotNull] SQLParser.BasicSelectStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.basicSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicSelectStatement([NotNull] SQLParser.BasicSelectStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.joinedSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedSelectStatement([NotNull] SQLParser.JoinedSelectStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.joinedSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedSelectStatement([NotNull] SQLParser.JoinedSelectStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.basicSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicSelector([NotNull] SQLParser.BasicSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.basicSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicSelector([NotNull] SQLParser.BasicSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.joinedSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedSelector([NotNull] SQLParser.JoinedSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.joinedSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedSelector([NotNull] SQLParser.JoinedSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.basicTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicTargetter([NotNull] SQLParser.BasicTargetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.basicTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicTargetter([NotNull] SQLParser.BasicTargetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.joinedTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedTargetter([NotNull] SQLParser.JoinedTargetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.joinedTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedTargetter([NotNull] SQLParser.JoinedTargetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.joinedMatcher"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedMatcher([NotNull] SQLParser.JoinedMatcherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.joinedMatcher"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedMatcher([NotNull] SQLParser.JoinedMatcherContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.whereLookup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhereLookup([NotNull] SQLParser.WhereLookupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.whereLookup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhereLookup([NotNull] SQLParser.WhereLookupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.asStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsStatement([NotNull] SQLParser.AsStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.asStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsStatement([NotNull] SQLParser.AsStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.variableAssignmentIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableAssignmentIdentifier([NotNull] SQLParser.VariableAssignmentIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.variableAssignmentIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableAssignmentIdentifier([NotNull] SQLParser.VariableAssignmentIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.specificIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecificIdentifier([NotNull] SQLParser.SpecificIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.specificIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecificIdentifier([NotNull] SQLParser.SpecificIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] SQLParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] SQLParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.boolFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolFunction([NotNull] SQLParser.BoolFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.boolFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolFunction([NotNull] SQLParser.BoolFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] SQLParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] SQLParser.VariableContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
