//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GrammarBaseListener : IGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] GrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] GrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.basicSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicSelectStatement([NotNull] GrammarParser.BasicSelectStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.basicSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicSelectStatement([NotNull] GrammarParser.BasicSelectStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.joinedSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedSelectStatement([NotNull] GrammarParser.JoinedSelectStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.joinedSelectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedSelectStatement([NotNull] GrammarParser.JoinedSelectStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.basicSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicSelector([NotNull] GrammarParser.BasicSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.basicSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicSelector([NotNull] GrammarParser.BasicSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.joinedSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedSelector([NotNull] GrammarParser.JoinedSelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.joinedSelector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedSelector([NotNull] GrammarParser.JoinedSelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.basicTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicTargetter([NotNull] GrammarParser.BasicTargetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.basicTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicTargetter([NotNull] GrammarParser.BasicTargetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.joinedTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinedTargetter([NotNull] GrammarParser.JoinedTargetterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.joinedTargetter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinedTargetter([NotNull] GrammarParser.JoinedTargetterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.bextidentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBextidentifier([NotNull] GrammarParser.BextidentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.bextidentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBextidentifier([NotNull] GrammarParser.BextidentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varassidentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarassidentifier([NotNull] GrammarParser.VarassidentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varassidentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarassidentifier([NotNull] GrammarParser.VarassidentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.sidentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSidentifier([NotNull] GrammarParser.SidentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.sidentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSidentifier([NotNull] GrammarParser.SidentifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
