//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.basicSelectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicSelectStatement([NotNull] GrammarParser.BasicSelectStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.basicSelectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicSelectStatement([NotNull] GrammarParser.BasicSelectStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.joinedSelectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinedSelectStatement([NotNull] GrammarParser.JoinedSelectStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.joinedSelectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinedSelectStatement([NotNull] GrammarParser.JoinedSelectStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.basicSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicSelector([NotNull] GrammarParser.BasicSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.basicSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicSelector([NotNull] GrammarParser.BasicSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.joinedSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinedSelector([NotNull] GrammarParser.JoinedSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.joinedSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinedSelector([NotNull] GrammarParser.JoinedSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.basicTargetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicTargetter([NotNull] GrammarParser.BasicTargetterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.basicTargetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicTargetter([NotNull] GrammarParser.BasicTargetterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.joinedTargetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinedTargetter([NotNull] GrammarParser.JoinedTargetterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.joinedTargetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinedTargetter([NotNull] GrammarParser.JoinedTargetterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.bextidentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBextidentifier([NotNull] GrammarParser.BextidentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.bextidentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBextidentifier([NotNull] GrammarParser.BextidentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varassidentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarassidentifier([NotNull] GrammarParser.VarassidentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varassidentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarassidentifier([NotNull] GrammarParser.VarassidentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.sidentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSidentifier([NotNull] GrammarParser.SidentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.sidentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSidentifier([NotNull] GrammarParser.SidentifierContext context);
}
